In [24]:
### Check Version
import sys
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(sys.version)
!python3 --version
print('numpy',np.__version__)
print('sklearn',sklearn.__version__)

3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
Python 3.8.10
numpy 1.22.2
sklearn 1.0.2


In [25]:
data=pd.read_csv('FinalDataSet.csv')
data.head(10)

STATE/UT  YEAR AGE_GROUP  GENDER  MURDER  ROBBERY  \
0  ANDAMAN & NICOBAR ISLANDS  2002  Below 18    MALE       3       16   
1  ANDAMAN & NICOBAR ISLANDS  2002  Below 18  FEMALE       0        1   
2  ANDAMAN & NICOBAR ISLANDS  2002  18 to 60    MALE      12      140   
3  ANDAMAN & NICOBAR ISLANDS  2002  18 to 60  FEMALE       3        1   
4  ANDAMAN & NICOBAR ISLANDS  2002  Above 60    MALE       0        1   
5  ANDAMAN & NICOBAR ISLANDS  2002  Above 60  FEMALE       0        1   
6  ANDAMAN & NICOBAR ISLANDS  2003  Below 18    MALE       4       19   
7  ANDAMAN & NICOBAR ISLANDS  2003  Below 18  FEMALE       0        1   
8  ANDAMAN & NICOBAR ISLANDS  2003  18 to 60    MALE      15      167   
9  ANDAMAN & NICOBAR ISLANDS  2003  18 to 60  FEMALE       3        1   

   KIDNAPP  FRAUD  VIOLENCE  
0        1      1         1  
1        1      1         1  
2        3     15       120  
3        1      1         5  
4        1      1         5  
5        1      1         1  
6        1      1         1  
7        1      1         1  
8        4     16       135  
9        1      1         6

In [26]:
from sklearn.preprocessing import LabelEncoder
l1, l2, l3 = LabelEncoder(), LabelEncoder(), LabelEncoder()

data['GENDER'] = l1.fit_transform(data['GENDER'])
data['STATE/UT'] = l2.fit_transform(data['STATE/UT'])
data['AGE_GROUP'] = l2.fit_transform(data['AGE_GROUP'])

In [27]:
X=data.iloc[:,[0,1,2,3]].values

X

array([[   0, 2002,    2,    1],
       [   0, 2002,    2,    0],
       [   0, 2002,    0,    1],
       ...,
       [  34, 2012,    0,    0],
       [  34, 2012,    1,    1],
       [  34, 2012,    1,    0]])

In [51]:
y=data.iloc[:,[4,5,6,7,8]].values
y

array([[   3,   16,    1,    1,    1],
       [   0,    1,    1,    1,    1],
       [  12,  140,    3,   15,  120],
       ...,
       [ 180,   44,  709,  366, 9376],
       [  37,   88,   92,   85,  812],
       [   5,   32,   13,   13,  170]])

### Data Split

In [52]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1)

ValueError: Found input variables with inconsistent numbers of samples: [1000, 2496]

In [50]:
X_train.shape, X_test.shape

((800, 10), (200, 10))

In [42]:
from sklearn.multioutput import RegressorChain
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(X_train,y_train)

ValueError: y should be a 1d array, got an array of shape (1996, 5) instead.

In [43]:
# linear regression for multioutput regression
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=10, n_informative=5, n_targets=2, random_state=1, noise=0.5)
#

In [45]:
X[0]

array([ 0.21947749,  0.32948997,  0.81560036,  0.440956  , -0.0606303 ,
       -0.29257894, -0.2820059 , -0.00290545,  0.96402263,  0.04992249])

In [46]:
y[0]

array([49.93137149, 64.08484989])